### ISSUE TITLE
I cannot get rid of the white border 

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/fancy-hover-boxes#1]
Hi, I think that the images are not fit the frame proportionally that they leave some white spaces that I cannot get rid of them. I'm so close right now.
![Screen Shot 2020-11-23 at 2 07 29 PM](https://user-images.githubusercontent.com/55094125/99936226-3b1c0080-2d95-11eb-958c-ab19c23aa079.png)

@hellachella
@HannahDelaney
@MacKenzieRose

**Comment by HannahDelaney** [comment]
Hey Sam! You'll need to add `display: block`. I'm not sure why, but inline-block adds a weird extra piece of space, and I'm fairly certain images are `display: inline-block` by default. So, if you add `display: block` to your images it should go away!

**Comment by Sam-Le68** [comment]
I did what you said but it didn't solve my issue at all ;-;

@hellachella
@HannahDelaney
@MacKenzieRose

**Comment by MacKenzieRose** [comment]
It looks like you added `display: block` to your image hover state, and not the image. 

Add it around line 42-45 in your CSS and the extra space should disappear 🙂

**Comment by Sam-Le68** [comment]
oh it's perfect now, thank you
